# Generated by Django 3.2.24 on 2024-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
